on:
  push:
    branches:
      - main

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag
      uses: ./.github/actions/semver-tag
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        version_file_location: ./
        create-major-tag: true
        create-latest-tag: true
