on:
  push:
    branches:
      - main

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Tag
      uses: andylolz/github-tag-action@v6.2-208-conventionalcommits-preset.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: "v"
        commit_sha: ${{ github.sha }}